cur = {'BO': {'country': 'Bolivia',
                   'currency_code': 'BOB',
                   'currency_name': 'Bolivian Boliviano',
                   'locale_name': 'BO'},
       'BN': {'country': 'Brunei',
                  'currency_code': 'BND',
                  'currency_name': 'Brunei Dollar',
                  'locale_name': 'BN'},
       'CF': {'country': 'CEMAC',
                 'currency_code': 'XAF',
                 'currency_name': 'Central African CFA Franc',
                 'locale_name': 'CF'},
       'CZ': {'country': 'Czech Republic',
                          'currency_code': 'CZK',
                          'currency_name': 'Czech Koruna',
                          'locale_name': 'CZ'},
       'CD': {'country': 'Democratic Republic of the '
                                            'Congo',
                                            'currency_code': 'CDF',
                                            'currency_name': 'Congolese Franc',
                                            'locale_name': 'CD'},
       'EU': {'country': 'European Union',
                          'currency_code': 'EUR',
                          'currency_name': 'Euro',
                          'locale_name': 'EU'},
       'FK': {'country': 'Falkland Islands',
                            'currency_code': 'FKP',
                            'currency_name': 'Falkland Islands Pound',
                            'locale_name': 'FK'},
       'IR': {'country': 'Iran',
                'currency_code': 'IRR',
                'currency_name': 'Iranian Rial',
                'locale_name': 'IR'},
       'LA': {'country': 'Laos',
                'currency_code': 'LAK',
                'currency_name': 'Lao Kip',
                'locale_name': 'LA'},
       'MO': {'country': 'Macau',
                 'currency_code': 'MOP',
                 'currency_name': 'Macanese Pataca',
                 'locale_name': 'MO'},
       'MD': {'country': 'Moldova',
                   'currency_code': 'MDL',
                   'currency_name': 'Moldovan Leu',
                   'locale_name': 'MD'},
       'AN': {'country': 'Netherlands Antilles',
                                'currency_code': 'ANG',
                                'currency_name': 'Netherlands Antillian Guilder',
                                'locale_name': 'AN'},
       'RU': {'country': 'Russia',
                  'currency_code': 'RUB',
                  'currency_name': 'Russian Ruble',
                  'locale_name': 'RU'},
       'SH': {'country': 'Saint Helena',
                        'currency_code': 'SHP',
                        'currency_name': 'Saint Helena Pound',
                        'locale_name': 'SH'},
       'KR': {'country': 'South Korea',
                       'currency_code': 'KRW',
                       'currency_name': 'South Korean Won',
                       'locale_name': 'KR'},
       'SY': {'country': 'Syria',
                 'currency_code': 'SYP',
                 'currency_name': 'Syrian Pound',
                 'locale_name': 'SY'},
       'ST': {'country': 'São Tomé and Príncipe',
                                 'currency_code': 'STN',
                                 'currency_name': 'São Tomé and Príncipe Dobra',
                                 'locale_name': 'ST'},
       'TW': {'country': 'Taiwan',
                  'currency_code': 'TWD',
                  'currency_name': 'New Taiwan Dollar',
                  'locale_name': 'TW'},
       'TZ': {'country': 'Tanzania',
                    'currency_code': 'TZS',
                    'currency_name': 'Tanzanian Shilling',
                    'locale_name': 'TZ'},
       'GM': {'country': 'The Gambia',
                      'currency_code': 'GMD',
                      'currency_name': 'Gambian Dalasi',
                      'locale_name': 'GM'},
       'VE': {'country': 'Venezuela',
                     'currency_code': 'VES',
                     'currency_name': 'Venezuelan Bolívar Soberano',
                     'locale_name': 'VE'},
       'VN': {'country': 'Vietnam',
                   'currency_code': 'VND',
                   'currency_name': 'Vietnamese Đồng',
                   'locale_name': 'VN'}}



       'CFA': {'country': 'CFA',
               'currency_code': 'XOF',
               'currency_name': 'West African CFA franc',
               'locale_name': 'Not found'},
       'Cape Verde': {'country': 'Cape Verde',
                      'currency_code': 'CVE',
                      'currency_name': 'Cape Verdean Escudo',
                      'locale_name': 'Not found'},
       "Collectivités d'Outre-Mer": {'country': "Collectivités d'Outre-Mer",
                                     'currency_code': 'XPF',
                                     'currency_name': 'CFP Franc',
                                     'locale_name': 'Not found'},

                                            'Organisation of Eastern Caribbean States': {'country': 'Organisation of '
                                                    'Eastern Caribbean '
                                                    'States',
                                                    'currency_code': 'XCD',
                                                    'currency_name': 'East Caribbean '
                                                               'Dollar',
                                                    'locale_name': 'Not found'},

                                                           'International Monetary Fund': {'country': 'International Monetary Fund',
                                       'currency_code': 'XDR',
                                       'currency_name': 'Special Drawing Rights',
                                       'locale_name': 'Not found'},